# Generated by Django 2.1 on 2019-06-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='category',
        ),
        migrations.AddField(
            model_name='step',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.Challenge'),
            preserve_default=False,
        ),
    ]
