# Generated by Django 2.1 on 2019-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190612_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='call_to_action_md',
            new_name='call_to_action_md_en',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='description_md',
            new_name='description_md_en',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='title_md',
            new_name='title_md_en',
        ),
        migrations.AddField(
            model_name='step',
            name='call_to_action_md_cn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='call_to_action_md_es',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='description_md_cn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='description_md_es',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='title_md_cn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='title_md_es',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
