# Generated by Django 2.1 on 2019-06-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190612_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='strategy_field_1_cn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 1 (chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_1_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 1 (english)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_1_es',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 1 (spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_2_cn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 2 (chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_2_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 2 (english)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_2_es',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 2 (spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_3_cn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 3 (chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_3_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 3 (english)'),
        ),
        migrations.AddField(
            model_name='step',
            name='strategy_field_3_es',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strategy field 3 (spanish)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='call_to_action_md_cn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Call to action (chinese)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='call_to_action_md_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Call to action (english)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='call_to_action_md_es',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Call to action (spanish)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description_md_cn',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description (chinese)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description_md_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description (english)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='description_md_es',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description (spanish)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title_md_cn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title (chinese)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title_md_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title (english)'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title_md_es',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title (spanish)'),
        ),
    ]
