# Generated by Django 2.1 on 2019-06-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190627_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='order',
        ),
    ]
