# Generated by Django 2.1 on 2019-06-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_step_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='public_field_10_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 10 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_10_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 10 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_10_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 10 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_10_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 10 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_11_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 11 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_11_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 11 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_11_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 11 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_11_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 11 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_12_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 12 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_12_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 12 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_12_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 12 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_12_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 12 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_13_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 13 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_13_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 13 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_13_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 13 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_13_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 13 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_14_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 14 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_14_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 14 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_14_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 14 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_14_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 14 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_15_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 15 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_15_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 15 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_15_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 15 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_15_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 15 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_16_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 16 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_16_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 16 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_16_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 16 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_16_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 16 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_9_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 9 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_9_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 9 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_9_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 9 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_9_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 9 Meta Description'),
        ),
    ]
