# Generated by Django 2.1 on 2019-06-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20190627_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='public_field_17_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 17 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_17_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 17 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_17_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 17 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_17_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True,
                                   verbose_name='Public field 17 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_18_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 18 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_18_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 18 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_18_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 18 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_18_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True,
                                   verbose_name='Public field 18 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_19_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 19 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_19_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 19 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_19_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 19 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_19_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True,
                                   verbose_name='Public field 19 Meta Description'),
        ),
    ]
