# Generated by Django 2.1 on 2019-06-30 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_strategychoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategychoice',
            old_name='clip',
            new_name='step',
        ),
    ]
