# Generated by Django 2.1 on 2019-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190630_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategychoice',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
