# Generated by Django 2.1 on 2019-07-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20190701_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyresponse',
            old_name='name',
            new_name='zipcode',
        ),
    ]
