# Generated by Django 2.1 on 2019-08-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20190718_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('origin_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='origin_feedback', to='cms.Step')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Step')),
            ],
        ),
    ]
