# Generated by Django 2.1 on 2019-08-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_categoryfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfeedback',
            name='origin_step',
        ),
    ]
