# Generated by Django 2.1 on 2019-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_remove_categoryfeedback_origin_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='public_field_20_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 20 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_20_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 20 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_20_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 20 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_20_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 20 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_21_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 21 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_21_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 21 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_21_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 21 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_21_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 21 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_22_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 22 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_22_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 22 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_22_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 22 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_22_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 22 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_23_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 23 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_23_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 23 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_23_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 23 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_23_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 23 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_24_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 24 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_24_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 24 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_24_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 24 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_24_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 24 Meta Description'),
        ),
    ]
