# Generated by Django 2.1 on 2019-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20190917_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='private_field_5',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Private field 5'),
        ),
        migrations.AddField(
            model_name='step',
            name='private_field_5_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Private field 5 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_25_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 25 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_25_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 25 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_25_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 25 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_25_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 25 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_26_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 26 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_26_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 26 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_26_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 26 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_26_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 26 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_27_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 27 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_27_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 27 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_27_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 27 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_27_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 27 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_28_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 28 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_28_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 28 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_28_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 28 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_28_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 28 Meta Description'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_29_cn',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 29 (Chinese)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_29_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 29 (English)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_29_es',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Public field 29 (Spanish)'),
        ),
        migrations.AddField(
            model_name='step',
            name='public_field_29_meta_description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Public field 29 Meta Description'),
        ),
    ]
